theme: minima
title: All About Rahul
author: Rahul Malhotra
email: rahulmalhotra2003@icloudcom
description: > # this means to ignore newlines until "baseurl:"
  This site will showcase some fun information about me. 
  You will see my name, photo, social media, and some things about me from high school.

# social links
instagram_username: rahulm2003
github_username:  RahulM844

show_excerpts: true # set to false to remove excerpts on the homepage
